name: dotnet package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Create pkg
        run: dotnet pack -c Release /p:Version=1.1.0
        working-directory: ./application-pkg.application-pkg
      - name: Archive Nuget
        uses: actions/upload-artifact@v3
        with:
          name: pkg
          path: "**/*.nupkg"
          
      
