name: dotnet package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release -o out
      - name: Generate Package
        run: dotnet pack -c Release -o out -p:PackageVersion=1.0.3
      - name: Publish package
        run: dotnet nuget push application-pkg.1.0.3.nupkg --api-key ${{ secrets.API_KEY }} --source https://api.nuget.org/v3/index.json
      
